use_frameworks!

target 'XMPFramework_Example' do
  pod 'XMPFramework', :path => '../'

  target 'XMPFramework_Tests' do
    inherit! :search_paths

    
  end
end

# Post install
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'XMPFramework'
        puts "Setting `IOS_ENV` for: #{target.name}"
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'IOS_ENV=1']
      end
    end
  end
end
