# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10
branches:
  only: master
script:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- xctool -workspace Example/XMPFramework.xcworkspace -scheme XMPFramework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 
- xctool test -workspace Example/XMPFramework.xcworkspace -scheme XMPFramework-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
- pod spec lint --allow-warnings
