# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10
branches:
  only: master
script:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- set -o pipefail && xcodebuild -workspace Example/XMPFramework.xcworkspace -scheme XMPFramework-Example ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
- pod spec lint --allow-warnings
